### ISSUE TITLE
Add a Helm Chart for deploying Solr Clouds

### ISSUE THREAD

**Issue by HoustonPutman** [apache/solr-operator#112]
We currently have a Helm Chart to deploy the Solr Operator, but users still have to manually create yaml files for their clouds/collections/etc.

It would be great to have helm charts that allow for users to easily create new SolrClouds (with metrics or collections included possibly). That way creating a solr cloud is two calls maximum (one to install the operator via helm, one to install the cloud via helm).

**Comment by mogul** [comment]
Another reason for having a SolrCloud Helm chart is that it would be helpful in documenting all the available options (eg `ingressOptions`) which are not used in examples and tutorials, and which are not explicitly documented in the `docs/` folder... Having a place where everything functional is overridden, as in a Helm template, will lead to that functional YAML stanza (presumably under test!) being the same as documentation.
