### ISSUE TITLE
Support for HPA

### ISSUE THREAD

**Issue by vladiceanu** [apache/solr-operator#251]
### Context
As per [kubebuilder.io](https://book.kubebuilder.io/reference/generating-crd.html?highlight=scale#scale) documentation, our Solr CRD has [subresource](https://github.com/apache/solr-operator/blob/v0.2.8/helm/solr-operator/crds/crds.yaml#L8294) `scale` which allows us to `kubectl scale SolrCloud <name> --replicas=<number>`. However, in order to make use of HPA, we need to have another argument, called `selectorpath`. If `selectorpath` is not present, the HPA (v2) fails with the following message:
```
Conditions:
  Type           Status  Reason             Message
  ----           ------  ------             -------
  AbleToScale    True    SucceededGetScale  the HPA controller was able to get the target's current scale
  ScalingActive  False   InvalidSelector    the HPA target's scale is missing a selector

Events:
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Warning  SelectorRequired              14s (x7 over 104s)  horizontal-pod-autoscaler  selector is required
  Warning  FailedComputeMetricsReplicas  14s (x7 over 104s)  horizontal-pod-autoscaler  selector is required

```

### Why HPA?
Users should be able to use the HPA in order to scale a CR. Which metrics to be used, how the cores will be assigned/removed from Solr, (....), are different questions and are out of the scope here. The flow would look like this:

`custom metrics` ---> `HPA` --_(scale)_--> `solrCloud CR`

Custom metrics could be any metrics that the user considers appropriate for the scale operation (including `solr_*` metrics exposed by prometheus exporter and prometheus-adapter for example).

### Proposal
Let's add the argument `scale.selectorpath` in order to be able to use the HPA, as mentioned in the [kubebuilder documentation](https://book.kubebuilder.io/reference/generating-crd.html?highlight=scale#scale).

**Comment by vladiceanu** [comment]
@HoustonPutman could you please have a look and let us know what are your insights on this?

**Comment by HoustonPutman** [comment]
Yeah, we should definitely make the changes necessary to enable the HPA, especially if they are as easy as this.

I think the most painful part will be not overriding the replicas value in the operator. Currently we default `nil` `replicas` values (to 3 I think...), but if we want to enable HPA, then we would have to turn over the management of the `replicas` field to the HPA. We could probably have a field called `autoscale: true|false` that makes it so that the StatefulSet `replicas` field isn't defined. But it would be cool if we could implement this without requiring the user explicitly enable autoscaling via a field.

After reading more, I think my assumption above might be incorrect...

Do you want to get a PR started for this? If we can get it done soon, we can get it in for the `v0.3.0` release that is starting next week.

**Comment by vladiceanu** [comment]
> After reading more, I think my assumption above might be incorrect...

Actually, you're right about the field `replicas`. The CR object has the field `replicas`, and if we keep it as it is, then every time you do `kubectl apply` of the manifest that contains the CR, it will set `replicas` value for the CR back to the static value from the manifest. This is similar to `spec.replicas` from Deployment workload and HPA: you either use `spec.replicas` or `HPA`, not both.

To solve this, we could do the following: 
- as you mentioned, have an additional field in the spec, called `autoscale`, make it optional and by default `false`;
- make the `replicas` field optional for the user input. Either `autoscale: true` or `replicas: <value>` to be required;
- assign the HPA creation to the user, not the Operator;

I was able to make HPA working with the CR by adding just a few changes to the operator and CRD, however, with the `replicas` and `autoscale` fields changes we might have to add a couple more changes.

I will try to make the aforementioned changes - `replicas` field optional and introduce an additional field `autoscale` and test it in my local environment.

**Comment by vladiceanu** [comment]
I have made the changes and came to the following conclusion:
- there is no need for an additional field `autoscaler`, it will bring confusion to the user since the autoscaling doesn't happen on the Operator itself. HPA should remain as it is, a side process that performs an action on the object; just like Deployment + HPA;
- if a user wants to use HPA, simply don't set `spec.replicas` field in SolrCloud CR definition, it's optional;
- user should be responsible to set the HPA;
- recommended to be used the `autoscaling/v2beta2` version of HPA, as it supports custom metrics and many other tweaks can be applied to make the scale ops smoother;

**Comment by HoustonPutman** [comment]
Actually, after implementing the new "empty `spec.replicas`" logic, I'm not sure it's necessary at all. The HPA will set the `spec.replicas` field on the SolrCloud object, not the StatefulSet. Therefore we can continue defaulting our `spec.replicas` to 3, as we currently are. The HPA will just scale it up or scale it down accordingly.
