### ISSUE TITLE
Supply client cert for API calls to mTLS enabled Solr clusters

### ISSUE THREAD

**Issue by thelabdude** [apache/solr-operator#255]
If the Solr cluster requires mTLS, then the `http.Client` used by `api.go` needs to supply a client cert and optionally the Certificate Authority (CA) cert if not already trusted between client & server. This means adding the following config to the `http.Transport` object for the `http.Client`:
```
				TLSClientConfig: &tls.Config{
					ClientCAs:          caCertPool,
					Certificates:       []tls.Certificate{clientCert},
                                          ...
				},
```
The server(s) will need to be configured to trust the CA that issued the client cert.

**Comment by HoustonPutman** [comment]
Is this something that we need to setup with the solr-operator pod, or can it be done dynamically?
