### ISSUE TITLE
create an ARM64 build of Solr-operator

### ISSUE THREAD

**Issue by alittlec** [apache/solr-operator#257]
The container on docker hub today is only available as an amd64 build, can we make this multi-arch and support arm64?

**Comment by HoustonPutman** [comment]
Was actually thinking about this and you made the issue right before I created the RC1 for this next release.

I'll try to get this in for v0.3.0

**Comment by HoustonPutman** [comment]
So I'm building this into the release wizard. I'm not going to have this as a part of the regular docker workflow, unless someone requests it.

Will have this as a part of a PR for finishing touches for the releaseWizard.

You can see that the current release candidate image has both `linux/amd64` and `linux/arm64`:
https://hub.docker.com/repository/docker/apache/solr-operator/tags?page=1&ordering=last_updated

**Comment by alittlec** [comment]
Wow - that was quick! :-)

Great stuff HoustonPutman
