### ISSUE TITLE
0.3.0 or latter versions are not available in helm

### ISSUE THREAD

**Issue by drano** [apache/solr-operator#258]
When can we find solr-operator in 0.3.0 or latter version in helm? The repository https://solr.apache.org/charts has only versions 0.2.6 to 0.2.8

**Comment by HoustonPutman** [comment]
The release candidate for the v0.3.0 version is currently under vote. 0.3.0 will be released once the vote succeeds.

You can follow the [vote for the first release candidate](https://lists.apache.org/thread.html/rda8ce14cded2f655966d60c9274fe0111985557beda7da1e0854a8dd%40%3Cdev.solr.apache.org%3E), but that will likely fail and require a second release candidate. If you follow the Solr dev mailing list, you will see the second release candidate when it comes out. Hopefully we will have a successful release late this week or early next week!

**Comment by HoustonPutman** [comment]
The v0.3.0 Release is now out.
