### ISSUE TITLE
Ephemeral storage should extend to ZK instance

### ISSUE THREAD

**Issue by mogul** [apache/solr-operator#259]
When you specify the ephemeral storage type for a `solrcloud`, that should also extend to the Zookeeper instance that the `solr-operator` manages ([specified like this](https://github.com/pravega/zookeeper-operator#Deploy-a-sample-zookeeper-cluster-with-ephemeral-storage)).

(We noted this when the ZK pod did not start on AWS Fargate because it was trying to use a persistent volume claim, so the SolrCloud pod did not start either despite using `emptyDir`.)

**Comment by HoustonPutman** [comment]
Agreed. This is a good feature that should be included in v0.4.0.

We should expose all options for the Zookeeper storage, but default to `ephemeral`/`persistent` depending on what the SolrCloud uses.

**Comment by jward-bw** [comment]
> We should expose all options for the Zookeeper storage, but default to ephemeral/persistent depending on what the SolrCloud uses.

This is important, in our use-case we probably will have solr data on ephemeral but ZK on persistent.
