### ISSUE TITLE
None of the CRD Download Links work

### ISSUE THREAD

**Issue by schoeffm** [apache/solr-operator#267]
Hi all,

as it seems … none of the documented CRD download links seem to work.

i.e. https://solr.apache.org/operator/downloads/crds/v0.3.0/all-with-dependencies.yaml leads to a 404 (like all others)

**Comment by HoustonPutman** [comment]
We are trying to get this resolved as soon as possible.

In the meantime you can use: https://nightlies.apache.org/solr/release/operator/crds/v0.3.0/all-with-dependencies.yaml

**Comment by HoustonPutman** [comment]
The URLs are fixed!
