### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by vipulp86** [apache/solr-operator#273]
Apache Solr-Operator does support arm64, but zookeeper-operator being used as dependency is not arm64 https://github.com/pravega/pravega-operator. Request you to make solr-operator whole as arm64 supported. Thanks

**Comment by HoustonPutman** [comment]
This is definitely an issue to raise in https://github.com/pravega/zookeeper-operator/issues.

We don't build zookeeper operator images, so we have no impact on whether there is an arm64 image available.

When you make the issue there, you will likely want to request both their zookeeper and zookeeper-operator images be made for arm64.

**Comment by vipulp86** [comment]
Make sense !!! Thanks Houston
