### ISSUE TITLE
Use v1 of the k8s networking and extension APIs

### ISSUE THREAD

**Issue by mogul** [apache/solr-operator#277]
The `k8s.io/api/networking/v1beta1` API is unsupported in the latest versions of `nginx-ingress`, and the API will be unsupported from k8s 1.22.0+ For future-proofing against breakage, the solr-operator should start using `k8s.io/api/networking/v1` to specify ingresses. 

(Note v1 has only been supported since k8s 1.19.0+, so switching to using v1 would limit solr-operator to supporting 1.19.0+, unless you add special support for using v1beta1 on earlier versions, which could get messy to maintain.)

**Comment by mogul** [comment]
Looks like the same situation applies for `apiextensions.k8s.io/v1beta1`.

**Comment by HoustonPutman** [comment]
Agreed. I was waiting to make the change until it was reasonable to make 1.19 the minimum supported kubernetes version. I think once 1.22 is released we can make this change and stage it for the next minor release.

**Comment by HoustonPutman** [comment]
Note, when we make 1.19 the minimum kubernetes version supported, we can officially add support for the [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) 🎉

**Comment by chubbard** [comment]
Since 1.22 is now officially out and 1.22.1 is coming out on 8/19/2021 when will upgrading from beta to v1 take place?

**Comment by mogul** [comment]
I'm not sure I understand the constraint you're facing here...
> However the env-test that we use to spin up a "test" kubernetes cluster for our unit-tests uses a built-in binary of a test API server built before networking/v1 was introduced. So that means that we have to upgrade many dependencies, and possibly the entire version of Kubebuilder that we are using.

However, in case it helps: We use [KinD](https://kind.sigs.k8s.io/) to provision clusters where we develop and run tests that use the `solr-operator`. This has been better for us than using the Docker Desktop because then we have tight control over which version of k8s we're working with, and the same tooling is used during CI/CD under GitHub Actions (where Docker Desktop isn't available).

**Comment by HoustonPutman** [comment]
So we do use KinD for our integration Smoke Tests, and will definitely use it in the future whenever we introduce integration tests (#134). However the EnvTest setup is used for unit tests for Kubebuilder projects. It's not an actual kubernetes cluster, like DockerDesktop or KinD. It's a custom stripped down version of the API Server.

With the Upgrade to Kubebuilder 3, we will actually be able to test with any version of the EnvTest Kubernetes version (So we will be able to test with multiple versions, just like KinD), but for now we are stuck with a very old version that shipped with Kubebuilder 2. I believe after the upgrade, the unit tests will actually be able to work with a real Kubernetes cluster as well (but our unit tests do not support this currently.), if you want to run the unit tests with your KinD cluster.

The PR for the Kubebuilder upgrade is far to big to parse (#321), but good progress is being made. And hopefully we will be able to cut a v0.5.0 fairly shortly (maybe within a month or month and a half) to support the new Kubernetes versions.

**Comment by mogul** [comment]
Great to see this addressed. Thank you!
