### ISSUE TITLE
CRD metadata.annotations too long when updating using `kubectl apply`

### ISSUE THREAD

**Issue by sigram** [apache/solr-operator#278]
```
kubectl apply -f crds.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/solrbackups.solr.apache.org configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/solrprometheusexporters.solr.apache.org configured
The CustomResourceDefinition "solrclouds.solr.apache.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

This happens with the CRDs generated on the main branch. Using `kubectl replace -f crds.yaml` succeeds.

**Comment by sigram** [comment]
I just realized this is actually mentioned in `helm/solr-operator/README.md` but without this specific error. Feel free to close.

**Comment by HoustonPutman** [comment]
I'll close this for now. In case other users face the issue and search for this error, they can find this issue to resolve it 🙂

**Comment by jalshorji** [comment]
I'm getting same issue with replace as well

**Comment by vnagireddy-symphonize** [comment]
> I just realized this is actually mentioned in `helm/solr-operator/README.md` but without this specific error. Feel free to close.

@sigram Can you please elaborate?  I am trying resolve the same issue, and `kubectl replace -f` is not helping. :-(
