### ISSUE TITLE
Expose operator metrics

### ISSUE THREAD

**Issue by janhoy** [apache/solr-operator#307]
Users may want to monitor the operator health. See https://book.kubebuilder.io/reference/metrics.html for some docs about publishing Prometheus metrics.

No idea what metrics are most useful. Some counters for various operations and errors. Perhaps a gauge for number of SolrClouds deployed?

**Comment by HoustonPutman** [comment]
There is very good default support for Operator metrics in Kubebuilder 3. Now that the operator uses Kubebuilder 3, we should investigate adding the metrics service & sidecar to the helm chart.

**Comment by HoustonPutman** [comment]
I think we can close this with the default operator metrics to start, since they are actually quite comprehensive. (including reconcile errors) We can split off another issue to look into custom metrics.
