### ISSUE TITLE
Null Pointer when running Prometheus Exporter

### ISSUE THREAD

**Issue by pareekdevanshu** [apache/solr-operator#325]
After deploying solr cloud to our EKS cluster, we decided to add the the prometheus exporter as well, however it stops exporting metrics intermittently and fails with null pointer exception.
In the logs, there is no stacktrace, just this log statement 

_ERROR - 2021-09-24 14:57:27.651; org.apache.solr.prometheus.collector.SolrCollector; null
java.lang.NullPointerException_

It happens randomly and restarting the exporter pod fixes it.

**Comment by HoustonPutman** [comment]
This is likely an issue with the PrometheusExporter itself and not how the Solr Operator runs the PrometheusExporter.

What version of Solr are you using for the PrometheusExporter?

**Comment by pareekdevanshu** [comment]
we are using Solr verison 8.8.2.

**Comment by HoustonPutman** [comment]
This might be because the SolrPrometheusExporter doesn't listen on changes to the SolrCloud Resource. So if something about the SolrCloud changes, such as the TLS/BasicAuth/ZKConnectionString, the PrometheusExporter is not guaranteed to get the update until something about its own state changes.

This is being addressed in #321, though it's a giant and unrelated PR.

**Comment by pareekdevanshu** [comment]
I see that https://github.com/apache/solr-operator/pull/321 is merged, so the fix is available for us to try?

**Comment by HoustonPutman** [comment]
You can always try running the latest version on `main`, but I definitely wouldn't do so in production. In order to get a real release with this fix, you will have to wait for `v0.5.0`

**Comment by pareekdevanshu** [comment]
when can we expect `v0.5.0` to be available to use?

**Comment by HoustonPutman** [comment]
I would expect a release candidate to come out next week. And if that passes then the full release will be available late that week or early the next week
