### ISSUE TITLE
v0.6.0-prerelease crd file missing

### ISSUE THREAD

**Issue by parekhcoder** [apache/solr-operator#402]
I want to install v0.6.0-prerelease version. But below file is missing.

https://solr.apache.org/operator/downloads/crds/v0.6.0-prerelease/all-with-dependencies.yaml

**Comment by HoustonPutman** [comment]
So If you want to install a prerelease version of the Solr Operator, refer to the [development documentation](https://github.com/apache/solr-operator/blob/main/docs/development.md#build-the-solr-crds).

Though if you want to use a released version of the solr operator, refer to website for more information. https://solr.apache.org/operator/artifacts.html
