### ISSUE TITLE
Support ArgoCD for the CRDs

### ISSUE THREAD

**Issue by janhoy** [apache/solr-operator#410]
When deploying Solr-Operator in [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) using its Helm chart, you may get this error message:
> reason: CustomResourceDefinition.apiextensions.k8s.io "solrclouds.solr.apache.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

This is since ArgoCD uses `kubectl apply` by default, which then overflows some buffer. Explanation here: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes

The same does not happen during normal `helm install` since Helm uses another method of installing CRDs.

This is not a bug in solr-operator, but there seems to be a very simple workaround, by adding this annotation to all our CRDs:

```yaml
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
```

This will tell Argo to use `kubectl replace` instead of apply, circumventing this limitation.

**Comment by thelabdude** [comment]
Nice find @janhoy ! others have hit this as well, would be good to include

**Comment by janhoy** [comment]
Note, I have not tried this, so not sure whether it will work on CRD resources. The solr-operator chart has the huge `crds/crds.yaml` file, not sure whether Argo applies it in one go or iterates one resource at a time, respecting the `sync-options` per-resource  or per-file. It would be interesting to test though.

**Comment by janhoy** [comment]
I tried this for an umbrella chart we use, manually adding this annotation to all four CRDs. And it solved the issue, so I think this is the way to go.

If you manually "refresh" SolrCloud application inside ArgoCD, then it will not respect this annotation, you have to explicitly tick a checkbox. Perhaps we should add a tiny documentation in solr-operator about the CRDs being large and some tools (like Argo) may display an error. I suppose this github issue will now also be searchable :)

**Comment by HoustonPutman** [comment]
I imagine ArgoCD may also fix the "refresh" functionality, because that definitely seems like a bug.

Think this is a great idea!

**Comment by HoustonPutman** [comment]
Also these files are autogenerated, and it looks like controller-gen does not support adding annotations to the generated CRDs yet... https://github.com/kubernetes-sigs/controller-tools/issues/656 

I'm sure we can find a workaround until controller-gen supports it natively.
