### ISSUE TITLE
Incoherent naming for additional domainNames variable (code vs. documentation)

### ISSUE THREAD

**Issue by mmoscher** [apache/solr-operator#412]
Helm-Chart and CRD documentations mentions a `additionalDomainNames` variable to provide further domainNames.
However, the CRD itself parses additionalDomains only.

**Comment by HoustonPutman** [comment]
The approach we have to take (for back-compat as well as rules around minor & patch releases) is:

- For v0.5.1 update the documentation (#415)
- For v0.6.0 add the new field, and auto-populate with the value from the old field. Add upgrade notes, deprecate the old field. (#416)
- For v0.7.0 remove the old field from the CRD

**Comment by mmoscher** [comment]
@HoustonPutman thanks for taking over. I was the last week (unfortunately) on vacation and therefore could not take care of it.

Thank you!
