### ISSUE TITLE
How to load solrconfig.xml from configmap

### ISSUE THREAD

**Issue by jojay** [apache/solr-operator#414]
Hello, 
I am evaluating usage of solr-operator currently and so a question came up:

Docu: https://apache.github.io/solr-operator/docs/solr-cloud/solr-cloud-crd.html#override-built-in-solr-configuration-files
states and gives an example how to load solr.xml and or log4j2.xml from configmap. 
This works fine for me.
I was asking myself though, if it is also possible to load solrconfig.xml making use of the same approach, which apparently doesn`t work the same way.

So my question is: What is the recommended way to load solrconfig.xml from configmap. Do I overlook sth. how CRD would help me to do so?
I saw that it is possible to interact with solconfig.xml using variables. But the docu doesn`t state how to load another solrconfig.xml

Thank you very much for your reply in advance.

**Comment by HoustonPutman** [comment]
Configsets are stored in ZK and thus there's not really a need for the Solr Operator to manage them for you.

There are Solr APIs for managing configSets, and the `solrconfig.xml` contained in them:

- https://solr.apache.org/guide/8_11/configsets-api.html
- https://solr.apache.org/guide/8_11/config-api.html

**Comment by jojay** [comment]
@HoustonPutman Thank you very much for your feedback!

**Comment by AlessandroPerucchi** [comment]
@HoustonPutman  Hi,
Thank you for the feedback too, I was interested also to do it.
I've tried the config API, but... I could not change the following option: 

{"set-property":{"updateHandlerupdateLog.numRecordsToKeep":500}}

I received the following error message:  

      'updateHandlerupdateLog.numRecordsToKeep' is not an editable property

So is there a way with the Config API to add/update this property?

When I read the 'updateHandlerupdateLog' properties, I get the following:

{
  "responseHeader":{
    "status":0,
    "QTime":363},
  "config":{"updateHandlerupdateLog":{
      "numVersionBuckets":65536,
      "dir":""}}}

Which is the default in the SolrCloud operator.

I know this topic is closed, but I think that my question is related to it, or would it better to open a new issue for it?

Thank you very much for your reply in advance.

**Comment by HoustonPutman** [comment]
Probably not unfortunately. You can instead use the **configSet api** to make a fully new configSet for yourself instead of just updating one value.

However in future versions we will hopefully support loading configSets in via configMaps in Kubernetes. Follow [this Solr Improvement Proposal](https://cwiki.apache.org/confluence/display/SOLR/SIP-18%3A+A+Solr+Kubernetes+Module+for+native+integration) for more.

**Comment by paditechno** [comment]
Thanks! [paditechno.com](https://paditechno.com)
