### ISSUE TITLE
Helm chart 404 Not Found

### ISSUE THREAD

**Issue by vladiceanu** [apache/solr-operator#420]
Seems like Apache Solr helm registry isn't available: https://solr.apache.org/charts

When you access https://solr.apache.org/charts, It redirects to https://nightlies.apache.org/solr/release/helm-charts

```
Error: looks like "https://solr.apache.org/charts" is not a valid chart repository or cannot be reached: failed to fetch https://solr.apache.org/charts/index.yaml : 404 Not Found
```

**Comment by koelnconcert** [comment]
Similar problem when downloading the crd manifest: https://solr.apache.org/operator/downloads/crds/v0.5.0/all-with-dependencies.yaml

Redirect to nightlies.apache.org and then a 404 error.

**Comment by DirkDittmarMonday** [comment]
https://solr.apache.org/charts redirects to https://nightlies.apache.org/solr/release/helm-charts and there is no directory `/solr`

**Comment by HoustonPutman** [comment]
The ASF Infra team moved over to a new nightlies server without copying over the data. I have asked them to copy the data for the `/solr` folder, but I'm unsure how long it will take them to do it.

As for the future, we now know that `nightlies.apache.org` is not a stable place to put this data, I'll look into using a stable location soon.

**Comment by HoustonPutman** [comment]
Created a PR to solr-site to fix the CRD download redirect permanently (archives will never have an issue 🙂) - https://github.com/apache/solr-site/pull/72

**Comment by HoustonPutman** [comment]
Ok it looks like the ASF Infra team has migrated over our data, so I will go ahead and mark this as "fixed". But I will create another issue to move the CRDs and Helm charts out of the nightlies server.
