### ISSUE TITLE
Configuration option to convert the Solr installation into Load Balancer Type service without possessing a External DNS

### ISSUE THREAD

**Issue by sridhar-sid** [apache/solr-operator#459]
I'm running the suggested steps in a GKE cluster, I don't have a registered DNS, i just want to connect to solr using the External IPs which will be provided by the GKE cluster on running a pod as a Load Balancer type service. Is it possible with the existing setup?
@HoustonPutman

**Comment by HoustonPutman** [comment]
This duplicates https://github.com/apache/solr-operator/issues/400, will close and continue with the other issue.
