### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by nosvalds** [apache/solr-operator#465]
Documentation links seem to be broken. They are set as https://apache.github.io/solr-operator/docs/upgrade-notes.html most places, but that’s a 404 now, and removing `/docs` from the path works. So https://apache.github.io/solr-operator/upgrade-notes.html is working.

@HoustonPutman has opened an issue with the Apache Infra team (its a failure in their systems or Github, we haven't changed anything).

**Comment by HoustonPutman** [comment]
Here is a link to the ASF Infra [Jira Issue](https://issues.apache.org/jira/browse/INFRA-23579)

**Comment by HoustonPutman** [comment]
They seem to be working now! I guess github pushed a fix 🙂
