### ISSUE TITLE
Should the "OOM killer script" be added as default

### ISSUE THREAD

**Issue by alexangas** [apache/solr-operator#467]
Reviewing [Choosing Memory Heap Settings](https://solr.apache.org/guide/8_11/jvm-settings.html#choosing-memory-heap-settings) and wondering if it makes sense to set the "OOM killer script" as a default. (Nothing else stood out as a default but there may be more.)

The option probably looks like `-XX:OnOutOfMemoryError=/opt/docker-solr/scripts/oom_solr.sh`.

**Comment by HoustonPutman** [comment]
Starting with Solr 8.9, the OOM killer should run by default: [SOLR-14978](https://issues.apache.org/jira/browse/SOLR-14978)

What version are you running?

Note: It will still be hard to have a default policy for heap dumps, as those will likely be deleted when the pod is killed. If the logs are mapped to a volume, then they may be saved though...

**Comment by alexangas** [comment]
Thank you for the tip! I'm running a few different versions but they're all older than 8.9. I will configure this myself for these older versions.
