### ISSUE TITLE
Helm zk.provided.zookeeperPodPolicy documentation issues

### ISSUE THREAD

**Issue by alexangas** [apache/solr-operator#472]
Noticed that the affinity property on https://github.com/apache/solr-operator/blob/v0.6.0/helm/solr/README.md?plain=1#L180 looks wrong as this property is already described a few lines later.

There may be other issues as well, as `envVars` is documented but the values file contains `env`.

**Comment by HoustonPutman** [comment]
Thanks for finding these @alexangas !

Feel free to open a PR to fix them, but if not I can get to it eventually 🙂

**Comment by HoustonPutman** [comment]
Closed in https://github.com/apache/solr-operator/pull/482
