### ISSUE TITLE
zookeeper doesn't honour global.clusterDomain value and keeps looking for cluster.local

### ISSUE THREAD

**Issue by parekhcoder** [apache/solr-operator#474]
getting error while installing solr,  Couldn't bind to solrcloud-zookeeper-headless.namespace.svc.cluster.local:2888.

Though provided global.clusterDomain setting it is still looking at cluster.local. (addressability.kubeDomain also doesn't work)

There doesn't have any param for clusterDomain in "zk" https://github.com/apache/solr-operator/blob/v0.6.0/helm/solr/README.md?plain=1#L152; though zookeeper does have param https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/README.md?plain=1#L63

**Comment by HoustonPutman** [comment]
Could you run `kubectl describe zookeepercluster`? In the code, the Solr Operator should be doing the right thing here: https://github.com/apache/solr-operator/blob/v0.6.0/controllers/util/zk_util.go#L119

**Comment by necipakca** [comment]
In my case 

  solrAddressability:
    kubeDomain: my-customdomain

works fine. Without any issue.

**Comment by HoustonPutman** [comment]
Thanks for your input here @necipakca !
