### ISSUE TITLE
Zookeeper pod label customization not working

### ISSUE THREAD

**Issue by endzyme** [apache/solr-operator#490]
## Description

When trying to apply custom labels to Zookeeper pods through the SolrCloud spec, the labels do not show up on the final set of Zookeeper pods. 

The issue appears to be that the Zookeeper Operator is not propagating the `zookeepercluster.spec.pod.labels` fields, but only applying labels which are defined in `zookeepercluster.spec.labels`.

## Related Issues

https://github.com/apache/solr-operator/issues/148
https://github.com/pravega/zookeeper-operator/issues/511

## Possible Solutions / Workarounds

Solution: Zookeeper Operator fixes the code to ensure the `pod.labels` are applied to the final StatefulSet for the Zookeeper ensemble.

Workaround: Change the Solr Operator to create the ZookeeperCluster custom resource to apply labels to `zookeepercluster.spec.labels` instead of `zookeepercluster.spec.pod.labels`.

**Comment by HoustonPutman** [comment]
Thanks for finding this issue!

This sounds like a good workaround, since it doesn't look like they will fix the issue soon.

Would you mind making a PR for this?

**Comment by HoustonPutman** [comment]
The Zookeeper Operator fix for this issue was released in [v0.2.15](https://github.com/pravega/zookeeper-operator/releases/tag/v0.2.15).

Once #549 is complete, we can remove this workaround before it is released in `v0.7.0`.
