### ISSUE TITLE
[Feature] Cross Collection Join Query to return Filter Fields

### ISSUE THREAD

**Issue by ivanspasov99** [apache/solr-operator#500]
Is it possible to have the option in the Cross Collection Join Query to return the joined fields also? I have succeeded in filtering by field in another collection which tells me that on runtime Solr have information about that field. Why not to returned it also? 

Example: `fq={!join from=id fromIndex=movie_directors to=director_id}has_oscar:true`. If we can have option to return `has_oscar` or other field we query on. 

Technical to have the option to join (fields) collection on filtering (similar to relational db join). It would be really useful in big distributed system with multiple collections.

**Comment by HoustonPutman** [comment]
This is a question for the [Solr Users list](https://solr.apache.org/community.html#mailing-lists-chat). The Solr Operator project only deals with runtime issues of running Solr in Kubernetes.
