### ISSUE TITLE
solr-operator-zookeeper-operator-pre-delete job node selector

### ISSUE THREAD

**Issue by arogic** [apache/solr-operator#503]
Hi,
We have an AKS Kubernetes Cluster with Linux and Windows Node Pools. We deploy the zookeeper-operator helm chart through the solr-operator helm chart. When we delete the solr-operator using helm, the "solr-operator-zookeeper-operator-pre-delete" job gets scheduled on the Windows NodePool which obviously fails. 

Is there a way to pass NodeSelector values over for the "solr-operator-zookeeper-operator-pre-delete" job to be scheduled on the Linux Node Pool?

Thanks in advance

**Comment by arogic** [comment]
Thanks @HoustonPutman. I got around the issue by adding node taint on my aks windows node pool.

`
    "node_taints": [
      "app.kubernetes.io/name=solr:NoSchedule"
    ]
`

**Comment by HoustonPutman** [comment]
Awesome, thanks for sharing your fix!
