### ISSUE TITLE
security.json isn't exported to Zookeeper

### ISSUE THREAD

**Issue by georgekaz** [apache/solr-operator#505]
security.json isn't exported to Zookeeper because the logic `if [ ${#ZK_SECURITY_JSON} -lt 3 ]` [here](https://github.com/apache/solr-operator/blob/1a8661bab03656f55a3352835b8496d5e6757f9d/controllers/util/solr_security_util.go#L211) is always false because of the log4j entries. In my example below, it's 345 even when it's empty.

```
solr@dev-solrcloud-0:/tmp$ ZK_SECURITY_JSON=$(/opt/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost dev-solrcloud-zookeeper-0.dev-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181,dev-solrcloud-zookeeper-1.dev-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181,dev-solrcloud-zookeeper-2.dev-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181/ -cmd get /security.json); echo "${ZK_SECURITY_JSON}"
2022-12-13 17:02:20.232 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2022-12-13 17:02:20.331 INFO  (zkConnectionManagerCallback-2-thread-1) [   ] o.a.s.c.c.ConnectionManager zkClient has connected
2022-12-13 17:02:20.331 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
{}
solr@dev-solrcloud-0:/tmp$ ZK_SECURITY_JSON=$(/opt/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost dev-solrcloud-zookeeper-0.dev-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181,dev-solrcloud-zookeeper-1.dev-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181,dev-solrcloud-zookeeper-2.dev-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181/ -cmd get /security.json); echo "${#ZK_SECURITY_JSON}"
345
```

Setting [custom log configuration](https://github.com/apache/solr-operator/blob/8381105fa129cd0e42b383a899900a07387a0e65/docs/solr-cloud/solr-cloud-crd.md#custom-log-configuration) doesn't help either because the env var and configmap volume don't get included in the init container.
```
configMapOptions:
  providedConfigMap: custom-solr-xml
```

Currently using the v0.6.0 of solr and solr-operator helm charts.

**Comment by HoustonPutman** [comment]
Thanks for reporting this!

So looking at the [log4j file that the script uses](https://github.com/apache/solr/blob/main/solr/server/resources/log4j2-console.xml), it should be appending to std_err, which I hope would not get put into the variable...

Can you provide the Solr image version you are using?

**Comment by georgekaz** [comment]
Hi. I believe it was 8.4.0. My colleague @yauhen-vastraknutau-epam can confirm. This is the latest version supported by the version of an app we use (https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB0227897). He worked around it by upgraded the image temporarily to v9.0 to allow zookeeper to configure correctly and then reverted to the v8 image.

**Comment by yauhen-vastraknutau-epam** [comment]
Yep, we stick to Solr 8.4.0 but I found that if I deploy 9.x it did security bootstrapping and I was able to downgrade Solr to 8.4.0 after this. Tried before 8.8.1 - didn't work as well.

**Comment by HoustonPutman** [comment]
It looks like Sitecore supports 8.11.2, and there is a workaround for users that need that lower Solr version. I'm going to close this for now.
