### ISSUE TITLE
Slow restart of Solr Pod init_container cp-solr-xml chown

### ISSUE THREAD

**Issue by smoldenhauer-ish** [apache/solr-operator#537]
Solr Operator 0.6.0
In our deployments a restart of Solr Pods will take minutes up to half an hour.
The init container cp-solr-xml with the command
cp /tmp/solr.xml /tmp-config/solr.xml && chown -R 8983:8983
         /var/solr/data/backup-restore/local-collection-backups-1
esp. the recursive chown seems to be the cause.  We mitigated it a bit by cleaning up the backup volume regularly. But there are deployments with a larger number of collections (~400) and then it is still slow.
...
The backup repository is a azurefile-csi storage.  

mailing list discussion: https://lists.apache.org/thread/tlxg38v6y81dhykycrgqw77mm2xdoqbr

**Comment by smoldenhauer-ish** [comment]
basic idea is to skip the chown if the backup directory is already writable for the solr user.

**Comment by HoustonPutman** [comment]
Yeah, sounds like a good improvement! Looks like you are testing out some options, so make a PR when you are ready.

**Comment by smoldenhauer-ish** [comment]
The changed statement is working now. I'm currently waiting for a test with forked custom image (0.6.0 + fix) in production deployment.

**Comment by HoustonPutman** [comment]
Awesome, make the PR when your tests are done! We will probably start the process for the v0.7.0 release late next week, and it would be great to have this included.

**Comment by HoustonPutman** [comment]
TODO: We should think about just using the [fsGroupChangePolicy](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods) available in Kubernetes v1.23

**Comment by smoldenhauer-ish** [comment]
I saw that [fsGroupChangePolicy](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods) = onRootMismatch , but wasn't sure how to apply that to the Solr backup PVC
It was kind of inspiration for the bugfix. 
If that would work, I guess the cp-solr-xml will be back to only copy the solr.xml

**Comment by HoustonPutman** [comment]
Yeah reading more through it, it seems like the default functionality is "Always", so its weird that it wouldn't be working in the first place. I guess we need to keep the logic in regardless.
