### ISSUE TITLE
Inconsistent data returned back when SOLR indexing is taking place

### ISSUE THREAD

**Issue by pratyushmck** [apache/solr-operator#552]
Hello Team, 

We are using the SOLR Cloud configuration for one of our use case, and are observing that our SOLR cluster is returning inconsistent data when indexing is taking place. Since we are new to SOLR, we are unable to identify the root cause of it. Can someone please help us understand potential debug steps to identify what could be the root cause of this issue.

Thanks,
Pratyush

**Comment by HoustonPutman** [comment]
I don't think there is an issue with the Solr Operator here.

Please use the [Solr Users mailing list](https://solr.apache.org/community.html#mailing-lists-chat) to ask issues with Solr itself. There are more people there that can help, but I would definitely recommend giving more information when you post there. The more information you give, the more help they can provide.
