### ISSUE TITLE
Solr Operator Upgrade - `kubectl create/replace VS kubectl apply/apply`

### ISSUE THREAD

**Issue by anilkhichar** [apache/solr-operator#572]
### kubectl create/replace VS kubectl apply/apply
Can we get real data points specific to solr operator CRDs where using apply can get wrong. Based on my experiment there is no difference in the applied CRD content.

My experiment steps:
Step1:
1. Install v0.5.1 CRD using kubeclt create -f
`kubeclt get crd -o yaml > *.yaml`
1. Upgrade to v0.6.0 CRD using kubeclt replace -f
`kubeclt get crd -o yaml > *.yaml`
1. Upgrade to v0.7.0 CRD using kubeclt replace -f
`kubeclt get crd -o yaml > *.yaml`

Step2:
1. Install v0.5.1 CRD using kubeclt apply -f
`kubeclt get crd -o yaml > *.yaml`
1. Upgrade to v0.6.0 CRD using kubeclt apply -f
`kubeclt get crd -o yaml > *.yaml`
1. Upgrade to v0.7.0 CRD using kubeclt apply -f
`kubeclt get crd -o yaml > *.yaml`

Step3, Step4: Also repeated steps from v0.3.0 to v0.7.0 (but same result)

Now the generated outcome YAML files do have exact same content except one `last-applied-cofiguration` extra element in the apply. And we don't need to worry about it.

![kubectl_apply_vs_replace_experiment](https://github.com/apache/solr-operator/assets/5746468/e06d8824-1ac9-4f8c-9b1f-ce5601d3422f)
![repalce_vs_apply_diff](https://github.com/apache/solr-operator/assets/5746468/20f63d74-5d73-4475-adad-7e6ce81a4375)

Other references: https://github.com/apache/solr-operator/issues/502

**Comment by HoustonPutman** [comment]
I'm not exactly sure what the goal of this issue is.

The recommended steps when installing the Solr Operator is to use `kubectl install` and the steps when upgrading the Solr Operator use `kubectl replace`.

The reason for this is that the last-applied-configuration can be too big for some Kubernetes instances, and those fields are useless for CRDs.
