### ISSUE TITLE
Bump minimum supported Solr version to 8.11

### ISSUE THREAD

**Issue by gerlowskija** [apache/solr-operator#616]
According to our [compatibility matrix](https://github.com/apache/solr-operator/blob/main/docs/upgrade-notes.md#solr-versions), Solr Operator 0.7.0 supports a huge range of Solr versions - stretching from Solr 9.3 all the way back to 7.7.

There's no need to support such a wide range.  And in fact there's a good bit of downside.  It dilutes our testing, and prevents the operator from relying on any Solr feature introduced in the last 2 or 3 years.  In fact, we've accumulated [quite a number of features we'd like to use](https://github.com/apache/solr-operator/blob/main/dev-docs/changes-for-minimum-solr-version.md) once our minimum version increases a bit.

It seems like a big jump, but 8.11 has been out for over a year and a half now (!).  Maybe we can target that as the minimum Solr version for operator 0.8.0.

If there's no objection to that plan, lets use this ticket to make the required changes to our docs.  And maybe as a parent/umbrella ticket for incorporating use of some of those Solr features we've been prevented from using up to this point.

**Comment by gerlowskija** [comment]
We've made pretty good progress on this via the linked issues.  There's one last change we can do (involving our ZK-bootstrapping) to make sure we're taking advantage of all that 8.11 offers, and then we can close this ticket out!

**Comment by HoustonPutman** [comment]
Thanks for all of the awesome work here Jason! Yeah one more and we should be good to go! (And the ZK Bootstrapping will be great to get rid of!!)

I think after that we should be good for the v0.8.0 release finally!

**Comment by HoustonPutman** [comment]
Unfortunately the Chroot initialization works for 8.11, but the zkCli commands break when the chroot is not pre-initialized ([SOLR-17019](https://issues.apache.org/jira/browse/SOLR-17019)). This will be fixed in 9.4 or 9.5, but there's no real reason to do that part until those issues are addressed.

So I think this ticket can be considered closed now!
