### ISSUE TITLE
Bring solr.xml into line with current Solr default settings.

### ISSUE THREAD

**Issue by gerlowskija** [apache/solr-operator#635]
The solr.xml that the operator currently uses as a default for new `solrcloud` resources was crafted in the Solr 7.x timeline.  [A recent issue](https://github.com/apache/solr-operator/issues/630) took some baby steps towards modernizing it, but it's still missing a number of settings that we can take advantage of now that our minimum Solr version is 8.11.  Particularly, sysprop-driven XML tags for "sharedLibs", "allowPaths", and "metrics".

Let's add these to our default solr.xml, so that users can drive these settings as desired through system properties.

**Comment by gerlowskija** [comment]
This is a sub-task of #635

**Comment by HoustonPutman** [comment]
100%! The allowPaths will be great as well, so that we can eventually utilize it for the backup paths, which currently reside in the data directory... But that is not required for this release.
