### ISSUE TITLE
Issue installing crd

### ISSUE THREAD

**Issue by jalshorji** [apache/solr-operator#647]
Getting same issue as in https://github.com/apache/solr-operator/issues/278 

kubectl replace didn't help

kubectl apply -f operators/crds.yaml
customresourcedefinition.apiextensions.k8s.io/solrbackups.solr.apache.org configured
customresourcedefinition.apiextensions.k8s.io/solrprometheusexporters.solr.apache.org configured
The CustomResourceDefinition "solrclouds.solr.apache.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

**Comment by HoustonPutman** [comment]
Can you paste the output of `kubectl replace -f operators/crds.yaml`?

**Comment by jalshorji** [comment]
The issue is solved. 
How ever, I have another issue. 
When I create solr and zookeeper 

apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: solr
spec:
  replicas: 4
  
and 

apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "zookeeper"
spec:
  replicas: 4
  
 It does not create any cores in solr. It seems like it cannot find managed-scheme and start searching for scheme.xml.  
 I get this error.
`solrcloud-node     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at java.lang.Thread.run(Unknown Source) [?:?]
solrcloud-node 2023-10-26 20:31:55.251 ERROR (qtp1171434979-82) [   ] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Error CREATEing SolrCore 'PreservationAgent_shard4_replica_n6': Unable to create core [PreservationAgent_shard4_replica_n6] Caused by: Can't find resource 'schema.xml' in classpath or '/configs/PreservationAgent', cwd=/opt/solr-8.11.2/server => org.apache.solr.common.SolrException: Error CREATEing SolrCore 'PreservationAgent_shard4_replica_n6': Unable to create core [PreservationAgent_shard4_replica_n6] Caused by: Can't find resource 'schema.xml' in classpath or '/configs/PreservationAgent', cwd=/opt/solr-8.11.2/server
solrcloud-node     at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1381)
solrcloud-node org.apache.solr.common.SolrException: Error CREATEing SolrCore 'PreservationAgent_shard4_replica_n6': Unable to create core [PreservationAgent_shard4_replica_n6] Caused by: Can't find resource 'schema.xml' in classpath or '/configs/PreservationAgent', cwd=/opt/solr-8.11.2/server
solrcloud-node     at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1381) ~[?:?]
solrcloud-node     at org.apache.solr.handler.admin.CoreAdminOperation.lambda$static$0(CoreAdminOperation.java:95) ~[?:?]
solrcloud-node     at org.apache.solr.handler.admin.CoreAdminOperation.execute(CoreAdminOperation.java:367) ~[?:?]
solrcloud-node     at org.apache.solr.handler.admin.CoreAdminHandler$CallInfo.call(CoreAdminHandler.java:397) ~[?:?]
solrcloud-node     at org.apache.solr.handler.admin.CoreAdminHandler.handleRequestBody(CoreAdminHandler.java:181) ~[?:?]
solrcloud-node     at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216) ~[?:?]
solrcloud-node     at org.apache.solr.servlet.HttpSolrCall.handleAdmin(HttpSolrCall.java:833) ~[?:?]
solrcloud-node     at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:797) ~[?:?]
solrcloud-node     at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:542) ~[?:?]
solrcloud-node     at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:427) ~[?:?]
solrcloud-node     at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:357) ~[?:?]
solrcloud-node     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
Stream closed EOF for default/solr-solrcloud-2 (cp-solr-xml)
solrcloud-node     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322) ~[jetty-rewrite-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solrcloud-node     at java.lang.Thread.run(Unknown Source) [?:?]
solrcloud-node Caused by: org.apache.solr.common.SolrException: Unable to create core [PreservationAgent_shard4_replica_n6]
solrcloud-node     at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1482) ~[?:?]
solrcloud-node     at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1342) ~[?:?]
solrcloud-node     ... 49 more
solrcloud-node Caused by: org.apache.solr.common.SolrException: Could not load conf for core PreservationAgent_shard4_replica_n6: Error loading both non-managed schema 'schema.xml' and managed schema 'managed-schema'
solrcloud-node     at org.apache.solr.core.ConfigSetService.loadConfigSet(ConfigSetService.java:100) ~[?:?]
solrcloud-node     at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1455) ~[?:?]
solrcloud-node     at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1342) ~[?:?]
solrcloud-node     ... 49 more
solrcloud-node Caused by: org.apache.solr.common.SolrException: Error loading both non-managed schema 'schema.xml' and managed schema 'managed-schema'
solrcloud-node     at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:171) ~[?:?]
solrcloud-node     at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:47) ~[?:?]
solrcloud-node     at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:157) ~[?:?]
solrcloud-node     at org.apache.solr.core.ConfigSetService.lambda$loadConfigSet$0(ConfigSetService.java:96) ~[?:?]
solrcloud-node     at org.apache.solr.core.ConfigSet.<init>(ConfigSet.java:48) ~[?:?]
solrcloud-node     at org.apache.solr.core.ConfigSetService.loadConfigSet(ConfigSetService.java:96) ~[?:?]
solrcloud-node     at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1455) ~[?:?]
solrcloud-node     at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1342) ~[?:?]
solrcloud-node     ... 49 more
solrcloud-node Caused by: org.apache.solr.core.SolrResourceNotFoundException: Can't find resource 'schema.xml' in classpath or '/configs/PreservationAgent', cwd=/opt/solr-8.11.2/server
solrcloud-node     at org.apache.solr.cloud.ZkSolrResourceLoader.openResource(ZkSolrResourceLoader.java:123) ~[?:?]
solrcloud-node     at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:153) ~[?:?]
solrcloud-node     at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:47) ~[?:?]
solrcloud-node     at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:157) ~[?:?]
solrcloud-node     at org.apache.solr.core.ConfigSetService.lambda$loadConfigSet$0(ConfigSetService.java:96) ~[?:?]
solrcloud-node     at org.apache.solr.core.ConfigSet.<init>(ConfigSet.java:48) ~[?:?]
solrcloud-node     at org.apache.solr.core.ConfigSetService.loadConfigSet(ConfigSetService.java:96) ~[?:?]
solrcloud-node     at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1455) ~[?:?]
solrcloud-node     at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1342) ~[?:?]
solrcloud-node     ... 49 more
solrcloud-node 2023-10-26 20:31:55.251 INFO  (qtp1171434979-82) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={qt=/admin/cores&coreNodeName=core_node8&collection.configName=PreservationAgent&newCollection=true&name=PreservationAgent_shard4_replica_n6&action=CREATE&numShards=4&collection=PreservationAgent&shard=shard4&wt=javabin&version=2&replicaType=NRT} status=400 QTime=129
solrcloud-node 2023-10-26 20:31:55.533 INFO  (qtp1171434979-80) [   x:PreservationAgent_shard4_replica_n6] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={deleteInstanceDir=true&deleteMetricsHistory=true&core=PreservationAgent_shard4_replica_n6&qt=/admin/cores&deleteDataDir=true&action=UNLOAD&wt=javabin&version=2} status=0 QTime=0
solrcloud-node 2023-10-26 20:31:55.761 INFO  (qtp1171434979-29) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/collections params={collection.configName=PreservationAgent&name=PreservationAgent&nrtReplicas=1&action=CREATE&numShards=4&wt=javabin&version=2} status=400 QTime=1204
solrcloud-node 2023-10-26 20:32:00.733 INFO  (qtp1171434979-55) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/health params={} status=0 QTime=0
solrcloud-node 2023-10-26 20:32:00.741 INFO  (qtp1171434979-82) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=8
solrcloud-node 2023-10-26 20:32:10.656 INFO  (qtp1171434979-60) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/health params={} status=0 QTime=0
solrcloud-node 2023-10-26 20:32:20.657 INFO  (qtp1171434979-27) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/health params={} status=0 QTime=0
solrcloud-node 2023-10-26 20:32:20.663 INFO  (qtp1171434979-25) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=6
solrcloud-node 2023-10-26 20:32:30.656 INFO  (qtp1171434979-31) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/health params={} status=0 QTime=0
solrcloud-node 2023-10-26 20:32:40.656 INFO  (qtp1171434979-28) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/health params={} status=0 QTime=0
solrcloud-node 2023-10-26 20:32:40.662 INFO  (qtp1171434979-59) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=5
`                             │

**Comment by HoustonPutman** [comment]
Are you sure you have uploaded your configSet correctly? I don't think this relates to the Solr Operator.

**Comment by jalshorji** [comment]
I havn't used any configSet, can you explain more? 
I just followed the tutorial

**Comment by HoustonPutman** [comment]
`Can't find resource 'schema.xml' in classpath or '/configs/PreservationAgent'` This error means that you are using a configSet called `PreservationAgent`. That isn't something that comes by default in Solr.

**Comment by jalshorji** [comment]
I understand. But should I get any cores in solr, because when I start solr UI it says No Cores Available

**Comment by HoustonPutman** [comment]
No, solr will not start with cores when first created, you have to create them by creating collections. You couldn't create the collection because there was an issue with your configSet, `PreservationAgent`.

**Comment by vnagireddy-symphonize** [comment]
@jalshorji Can you please shed some light on how you resolved the original issue of `The CustomResourceDefinition "solrclouds.solr.apache.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`?

**Comment by jalshorji** [comment]
@vnagireddy-symphonize  It worked with create instead of apply
