### ISSUE TITLE
User helm chart 0.8.0 with default values thorw the error in ValidationError(SolrCloud.spec): unknown field "scaling" in org.apache.solr.v1beta1.SolrCloud.spec

### ISSUE THREAD

**Issue by schotten** [apache/solr-operator#683]
Dear,
When i updated the helm chart version to 0.8.0 and apply in te Kubernets, the error trhowed:
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(SolrCloud.spec): unknown field "scaling" in org.apache.solr.v1beta1.SolrCloud.spec

I used the command line:
`helm  install solr-cluster apache-solr/solr --version 0.8.0 -f cluster_values_variables.yaml --namespace dev-namespace`

And used the default values in cluster_values_variables.yaml:
[cluster_values - Copia.txt](https://github.com/apache/solr-operator/files/14183322/cluster_values.-.Copia.txt)

Can you help me?

**Comment by HoustonPutman** [comment]
You first have to update the CRDs in your cluster, before updating the Solr Operator helm chart or you Solr cluster helm charts.

Docs - https://apache.github.io/solr-operator/docs/upgrade-notes.html#installing-the-solr-operator-vs-solr-crds
