### ISSUE TITLE
Disabling PodDisruptionBudgets for both zk pods and solr pods

### ISSUE THREAD

**Issue by crptz** [apache/solr-operator#699]
Hello everyone,

Docs specify that I can disable PodDisruptionBudgets by just setting 
`availability.podDisruptionBudget.enabled = false`

This disables only the Solr PodDisruptionBudgets and not the zk PodDisruptionBudgets.

If we read further on docs I can see we have:
`zk.provided.maxUnavailableReplicas` with default value to `1`

but there is no available value to specify to disable the PDB for zk.

Also changing the value of `zk.provided.maxUnavailableReplicas` it doesn't work either. I set the value to `0` and it doesn't change anything.

So how can I disable the PDB for zk?

Cheers

**Comment by HoustonPutman** [comment]
Have you checked with the zookeeper operator that they give an option to disable it?

**Comment by crptz** [comment]
sorry for my ignorance but are you referring to [these](https://github.com/pravega/zookeeper-operator/tree/master/charts/zookeeper-operator#configuration) values? 

They don't mention anything about podDisruptionBudget.

**Comment by HoustonPutman** [comment]
It would actually be the [zookeeper chart values](https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/README.md) but I don't see it there either. If the zookeeper operator doesn't give the ability to disable podDistruptionBudgets for zk clusters, there's really nothing we can do to help unfortunately.
