### ISSUE TITLE
Configure Resources for zookeeper operator

### ISSUE THREAD

**Issue by aloosnetmatch** [apache/solr-operator#708]
In our kubernetes environment , we require that "resources/requests" are configured.
That is not an option right now in the helm chart for the zookeeper operator for the following containers:

post-install-upgrade-hooks.yaml
pre-delete-hooks.yaml

**post-install-upgrade-hooks.yaml:**
spec:
  backoffLimit: {{ .Values.hooks.backoffLimit }}
  template:
    metadata:
      name: {{ template "zookeeper-operator.fullname" . }}-post-install-upgrade
    spec:
      serviceAccountName: {{ template "zookeeper-operator.fullname" . }}-post-install-upgrade
      restartPolicy: Never
      containers:
      - name: post-install-upgrade-job
        image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          **resources: 
            limits:
              # cpu: < optional value , like 1>
              memory: < optional value , like 512Mi>
            requests:
              cpu: < required value , like "500m" >
              memory: < required value , like 256Mi >****

**pre-delete-hooks.yaml:** 
spec:
  backoffLimit: 6
  template:
    metadata:
      name: {{ template "zookeeper-operator.fullname" . }}-pre-delete
    spec:
      serviceAccountName: {{ template "zookeeper-operator.fullname" . }}-pre-delete
      restartPolicy: Never
      containers:
        - name: pre-delete-job
          image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          **resources: 
            limits:
              # cpu: < optional value , like 1>
              memory: < optional value , like 512Mi>
            requests:
              cpu: < required value , like "500m" >
              memory: < required value , like 256Mi >****

I would like these values to be configurable from the values file.

**Comment by HoustonPutman** [comment]
If you are installing the zk-operator through the solr operator chart, then all Zookeeper Operator options will be available under `zookeeper-operator.*`.

If these are options that the Zookeeper Operator does not currently provide, please open an issue there: https://github.com/pravega/zookeeper-operator
