### ISSUE TITLE
Solr Restore Space Considerations in Kubernetes

### ISSUE THREAD

**Issue by mchennupati** [apache/solr-operator#726]
I am restoring a large index (655G) that is currently on google cloud storage to a new solr cloud on kubernetes instance.  I am trying to understand how much space I need to allocate to each of my node pvcs. 

I am currently using the collections api, with async to restore a collection saved in gcs.

When I check my disk usage for /var/solr/data on each of the nodes, it looks like this. So each of them appears to be downloading the entire index. I initially allocated 500G to each of the pvcs but that turned out to be too little. I am now doing it with 700G. 

Is this expected behaviour or am I doing something wrong ? One would have expected the metadata has enough information to download the index in parts and not do it 655G x 3.  It's cost me a fair bit in network costs already as I reiterate :)

In general, how would one restore a large index, I did not find a solrrestore similar to solrbackups in the solr operator crds. 

So I ran an async job using the solr collections api.

Thanks !

/var/solr/data$ du
4       ./userfiles
4       ./backup-restore/gcs-backups/gcscredential/..2024_10_11_06_16_24.1266852566
4       ./backup-restore/gcs-backups/gcscredential
8       ./backup-restore/gcs-backups
12      ./backup-restore
4       ./filestore
4       ./mycoll_shard3_replica_n3/data/tlog
4       ./mycoll_shard3_replica_n3/data/snapshot_metadata
8       ./mycoll_shard3_replica_n3/data/index
85744132        ./mycoll_shard3_replica_n3/data/restore.20241011062904489
85744152        ./mycoll_shard3_replica_n3/data
85744160        ./mycoll_shard3_replica_n3
85744192        .
solr@mycoll-solrcloud-0:/var/solr/data$ du -sh

**Comment by gerlowskija** [comment]
(Hi @mchennupati - it looks like the formatting on your post mangled a few things, so apologies if I'm missing something.)

afaict your question isn't necessarily related to using the operator for restores, it's just a question about the disk and network costs of restoring a Solr collection?  Assuming I've got that right - a better place to ask in the future would be our project's "user" mailing list: users@solr.apache.org.  Please subscribe and ask similar questions there going forward!

To your specific question: if you're restoring data to an existing collection, Solr will have each replica fetch data from the backup repository.  (So if you have three replicas each fetching a 100gb index, you'll pull 300gb from GCS).  Restores to a new collection work slightly differently, with only one replica fetching the index and then distributing it within your Solr cluster as needed.  So the network impact of restores can be tuned a little bit.

In terms of disk space though - ultimately all replicas of a shard will need a full copy of that shard's data, which sounds like 665GB in your case.

**Comment by mchennupati** [comment]
Thank you for your reply. Yes, I think i didnt quite understand how the
restore worked, but i figured it out eventually.

One aspect of my question still remains, perhaps its missing documentation.
The solr operator or a CRD allows one to do a backup. But a similar restore
doesnt exist or is missing from the docs ?

Thanks !

**Comment by gerlowskija** [comment]
You're not missing anything - there's no CRD support (currently) for triggering a restore.  Users interested in triggering a restore can use [the API exposed by Solr for that purpose](https://solr.apache.org/guide/solr/latest/deployment-guide/collection-management.html#restore).

Currently, the operator does its best to manage the nodes in a Solr cluster, but doesn't aim to manage anything that lives on those nodes, i.e. collections, cores, configsets, etc.  If there's interest in expanding the CRD/operator to cover those, maybe that'll happen at some point.  But there'd have to be a clear value prop I think.  I don't know that anyone's made a clear case for expanding to cover that stuff quite yet.

That's all to say - if you've got a good use-case for triggering restores via CRD fields, file an Issue and we can discuss there!  In the meantime, the Solr API should be sufficient!
