### ISSUE TITLE
Solr with 2 ports https - each port with different keystore

### ISSUE THREAD

**Issue by marcokonsultex** [apache/solr-operator#727]
Hello,

I am using Solr together with Alfresco Content ECM for indexing.

I have Solr installed manually on my server and generated a certificate by Alfresco to connect in trust through port 8983 https. This is working correctly.

Now I want to create another https output (connection) on port 443 on the Solr Server using the client certificate so that they can access the Solr Admin Console from anywhere.

Is there any documentation or roadmap so that I can do this?

I do not have an isolated Tomcat where Solr is installed. The installation of Solr together with Alfresco is a set of files in a .zip file. However, I have solcores.properties, solr.in.cmd, etc.

I also have 2 cores created for indexing.

Marco Gianini

**Comment by gerlowskija** [comment]
Hi @marcokonsultex - these sort of deployment-setup questions usually get the best response on our "user" mailing list which is seen by a lot more folks: `users@solr.apache.org`

I'd try asking your question there if you're still looking for help.  The more information you can include on your setup, the more likely it will be that someone will be able to help.  It'd be helpful to know your Solr version, your solr-operator version, operating system and other environmental details, etc.  Good luck!
