### ISSUE TITLE
metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by andrewrothstein** [apache/solr-operator#732]
kubectl apply -f "https://solr.apache.org/operator/downloads/crds/v0.8.1/a\
ll-with-dependencies.yaml"                                                                                                          
customresourcedefinition.apiextensions.k8s.io/solrbackups.solr.apache.org configured                                                
customresourcedefinition.apiextensions.k8s.io/solrprometheusexporters.solr.apache.org configured                                    
customresourcedefinition.apiextensions.k8s.io/zookeeperclusters.zookeeper.pravega.io configured                                     
The CustomResourceDefinition "solrclouds.solr.apache.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

**Comment by HoustonPutman** [comment]
Please refer to the answer here: https://github.com/apache/solr-operator/issues/502#issuecomment-1339758128
